"""user user_accounts mapping 3

Revision ID: 052ee7dc12ba
Revises: 492ca271d132
Create Date: 2024-03-04 16:26:17.762023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '052ee7dc12ba'
down_revision: Union[str, None] = '492ca271d132'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
