"""Initial migration Balance 5

Revision ID: 12b65fe29645
Revises: 78f88efead7c
Create Date: 2024-03-09 23:32:31.068473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12b65fe29645'
down_revision: Union[str, None] = '78f88efead7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_accounts', sa.Column('interest_rate', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_accounts', 'interest_rate')
    # ### end Alembic commands ###
