"""Initial migration Balance 2

Revision ID: 13fbda129e82
Revises: ac76bb148f59
Create Date: 2024-03-09 23:26:05.394839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13fbda129e82'
down_revision: Union[str, None] = 'ac76bb148f59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_accounts', sa.Column('interest_rate', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_accounts', 'interest_rate')
    # ### end Alembic commands ###
