"""Initial migration Account id foreign

Revision ID: 260c32eef41d
Revises: 6c94b0438df7
Create Date: 2024-03-10 19:48:29.360043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '260c32eef41d'
down_revision: Union[str, None] = '6c94b0438df7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'user_accounts', 'users', ['id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_accounts', type_='foreignkey')
    # ### end Alembic commands ###
