"""Initial migration Account email fk

Revision ID: 3a569c255f37
Revises: ed3a9d39c4e3
Create Date: 2024-03-10 22:15:37.442777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a569c255f37'
down_revision: Union[str, None] = 'ed3a9d39c4e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), sa.Identity(always=True, start=1), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('firstname', sa.String(), nullable=False),
    sa.Column('lastname', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username_acc', sa.String(), nullable=False),
    sa.Column('accounts', sa.String(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('interest_rate', sa.Float(), nullable=False),
    sa.Column('data_time', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['username_acc'], ['users.email'], ),
    sa.PrimaryKeyConstraint('id', 'username_acc'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('username_acc')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_accounts')
    op.drop_table('users')
    # ### end Alembic commands ###
