"""Initial migration Account time 3

Revision ID: 47845f30e5c1
Revises: acb3dcd4558c
Create Date: 2024-03-10 16:31:48.780164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47845f30e5c1'
down_revision: Union[str, None] = 'acb3dcd4558c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_accounts', 'data_time',
               existing_type=sa.DATE(),
               type_=sa.Float(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_accounts', 'data_time',
               existing_type=sa.Float(),
               type_=sa.DATE(),
               existing_nullable=False)
    # ### end Alembic commands ###
