"""user user_accounts mapping 2

Revision ID: 492ca271d132
Revises: e72c6e1e2d03
Create Date: 2024-03-04 16:23:25.563436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '492ca271d132'
down_revision: Union[str, None] = 'e72c6e1e2d03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
