"""Initial migration Account time 2

Revision ID: 608ca4b6afc3
Revises: 94a78d1e0f15
Create Date: 2024-03-10 00:44:28.033998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '608ca4b6afc3'
down_revision: Union[str, None] = '94a78d1e0f15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
