"""Initial migration Account email acc email2

Revision ID: 676b618babe4
Revises: d46a02ce0585
Create Date: 2024-03-10 23:21:08.283984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '676b618babe4'
down_revision: Union[str, None] = 'd46a02ce0585'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
