"""Initial migration Account time 3

Revision ID: 6c94b0438df7
Revises: 33bdf7cd066e
Create Date: 2024-03-10 16:42:55.168212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c94b0438df7'
down_revision: Union[str, None] = '33bdf7cd066e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_accounts', 'data_time',
               existing_type=sa.DATE(),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_accounts', 'data_time',
               existing_type=sa.Integer(),
               type_=sa.DATE(),
               existing_nullable=False)
    # ### end Alembic commands ###
