"""Initial migration Account email acc email 3

Revision ID: 8220ccedf6b3
Revises: 8f10517683f9
Create Date: 2024-03-10 23:28:57.265554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8220ccedf6b3'
down_revision: Union[str, None] = '8f10517683f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user_accounts', ['id'])
    op.drop_constraint('users_email_fkey', 'users', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('users_email_fkey', 'users', 'users', ['email'], ['email'])
    op.drop_constraint(None, 'user_accounts', type_='unique')
    # ### end Alembic commands ###
