"""Initial migration Account email acc email 4

Revision ID: 830defa5d6d1
Revises: 8220ccedf6b3
Create Date: 2024-03-10 23:32:04.308903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '830defa5d6d1'
down_revision: Union[str, None] = '8220ccedf6b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
