"""user user_accounts mapping 4

Revision ID: 93a5a28f86b4
Revises: 052ee7dc12ba
Create Date: 2024-03-04 16:53:18.023612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93a5a28f86b4'
down_revision: Union[str, None] = '052ee7dc12ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
