"""Initial migration Account time 2

Revision ID: 94a78d1e0f15
Revises: c1fcbc2102f5
Create Date: 2024-03-10 00:42:59.128407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94a78d1e0f15'
down_revision: Union[str, None] = 'c1fcbc2102f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
