"""Initial migration Account time 3

Revision ID: acb3dcd4558c
Revises: 608ca4b6afc3
Create Date: 2024-03-10 16:29:31.838982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acb3dcd4558c'
down_revision: Union[str, None] = '608ca4b6afc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_accounts', 'data_time',
               existing_type=sa.DATE(),
               type_=sa.Float(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_accounts', 'data_time',
               existing_type=sa.Float(),
               type_=sa.DATE(),
               existing_nullable=False)
    # ### end Alembic commands ###
