"""Initial migration Account time

Revision ID: c1fcbc2102f5
Revises: 12b65fe29645
Create Date: 2024-03-10 00:23:17.016550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1fcbc2102f5'
down_revision: Union[str, None] = '12b65fe29645'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_accounts', sa.Column('data_time', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_accounts', 'data_time')
    # ### end Alembic commands ###
