"""new  migration 3

Revision ID: c9f5854589da
Revises: 23d1d60a986d
Create Date: 2024-03-03 23:12:58.355621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9f5854589da'
down_revision: Union[str, None] = '23d1d60a986d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_accounts', sa.Column('interest_rate', sa.FLOAT(), nullable=False))
    op.drop_constraint('user_accounts_username_acc_fkey', 'user_accounts', type_='foreignkey')
    op.create_foreign_key(None, 'user_accounts', 'users', ['username_acc'], ['email'])
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['id'])
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.drop_constraint(None, 'user_accounts', type_='foreignkey')
    op.create_foreign_key('user_accounts_username_acc_fkey', 'user_accounts', 'users', ['username_acc'], ['username'])
    op.drop_column('user_accounts', 'interest_rate')
    # ### end Alembic commands ###
