"""user user_accounts mapping 

Revision ID: d6de75733e17
Revises: c184bb79af1f
Create Date: 2024-03-04 16:00:29.970836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6de75733e17'
down_revision: Union[str, None] = 'c184bb79af1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_accounts', sa.Column('interest_rate', sa.Float(), nullable=False))
    op.drop_constraint('user_accounts_username_acc_fkey', 'user_accounts', type_='foreignkey')
    op.drop_column('user_accounts', 'username_acc')
    op.add_column('users', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('users', 'firstname',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'firstname',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('users', 'id')
    op.add_column('user_accounts', sa.Column('username_acc', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_accounts_username_acc_fkey', 'user_accounts', 'users', ['username_acc'], ['username'])
    op.drop_column('user_accounts', 'interest_rate')
    # ### end Alembic commands ###
