"""user user_accounts mapping 1

Revision ID: e72c6e1e2d03
Revises: 807cfa1be8ef
Create Date: 2024-03-04 16:17:14.030492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e72c6e1e2d03'
down_revision: Union[str, None] = '807cfa1be8ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
