"""Initial migration Account email fk

Revision ID: e950965fd34e
Revises: 6b5b4a803d38
Create Date: 2024-03-10 22:09:36.663659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e950965fd34e'
down_revision: Union[str, None] = '6b5b4a803d38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_accounts', sa.Column('username_acc', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'user_accounts', ['username_acc'])
    op.drop_constraint('user_accounts_id_fkey', 'user_accounts', type_='foreignkey')
    op.create_foreign_key(None, 'user_accounts', 'users', ['username_acc'], ['email'])
    op.create_foreign_key(None, 'users', 'users', ['email'], ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'user_accounts', type_='foreignkey')
    op.create_foreign_key('user_accounts_id_fkey', 'user_accounts', 'users', ['id'], ['id'])
    op.drop_constraint(None, 'user_accounts', type_='unique')
    op.drop_column('user_accounts', 'username_acc')
    # ### end Alembic commands ###
