"""new  migration 6

Revision ID: faa58ee2905a
Revises: 476acae02393
Create Date: 2024-03-03 23:37:36.298871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faa58ee2905a'
down_revision: Union[str, None] = '476acae02393'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_accounts', sa.Column('interest_rate', sa.FLOAT(), nullable=False))
    op.alter_column('user_accounts', 'username_acc',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('user_accounts_username_acc_fkey', 'user_accounts', type_='foreignkey')
    op.create_foreign_key(None, 'user_accounts', 'users', ['username_acc'], ['email'])
    op.add_column('users', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.drop_column('users', 'id')
    op.drop_constraint(None, 'user_accounts', type_='foreignkey')
    op.create_foreign_key('user_accounts_username_acc_fkey', 'user_accounts', 'users', ['username_acc'], ['username'])
    op.alter_column('user_accounts', 'username_acc',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('user_accounts', 'interest_rate')
    # ### end Alembic commands ###
