"""Initial migration Account email acc email 3

Revision ID: fff283d3aaa6
Revises: 7a652a1e9687
Create Date: 2024-03-10 23:24:47.082828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fff283d3aaa6'
down_revision: Union[str, None] = '7a652a1e9687'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
